AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  python-kinesis-filter

  Sample SAM Template for python-kinesis-filter

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  # Define Lambda Function
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: kinesis_filter/ # folder in project
      Handler: app.lambda_handler # filename.methodname
      Runtime: python3.8
      Events: # Define trigger for lambda execution
        Stream:
          Type: Kinesis
          Properties:
            Stream: !GetAtt SourceStream.Arn
            BatchSize: 1000
            # MaximumBatchingWindowInSeconds: 30
            StartingPosition: LATEST
      Policies:
        - KinesisStreamReadPolicy:
            StreamName: !Ref SourceStream
        - KinesisCrudPolicy:
            StreamName: !Ref SinkStream
      Environment:
        Variables:
          SINKSTREAM: !Ref SinkStream
          SOURCESTREAM: !Ref SourceStream

  # Define input and output streams
  SourceStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: SourceStream
      ShardCount: 1
  SinkStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: SinkStream
      ShardCount: 1
# Outputs:
# ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
# Find out more about other implicit resources you can reference within SAM
# https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
# HelloWorldApi:
#   Description: "API Gateway endpoint URL for Prod stage for Hello World function"
#   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
# HelloWorldFunction:
#   Description: "Hello World Lambda Function ARN"
#   Value: !GetAtt HelloWorldFunction.Arn
# HelloWorldFunctionIamRole:
#   Description: "Implicit IAM Role created for Hello World function"
#   Value: !GetAtt HelloWorldFunctionRole.Arn
